### ISSUE TITLE
Using short closures limits PHP versions.

### ISSUE THREAD

**Issue by thinkverse** [use-preset/laravel-tailwindcss#3]
Hi there, just wanted to pop in say that maybe you should add a PHP version disclaimer somewhere, maybe a badge or something, since using short closures will limit the PHP version to 7.4+ and Laravel currently supports [^7.2.5], sure yes, users can go into the routes and change it themselves but would be nice to know beforehand. 🙂

https://github.com/use-preset/laravel-tailwindcss/blob/13191e7b1706a4b9188f3f9d7e0cfe92943b1cdb/templates/auth/routes/web.php#L19

Thank you for your time. 👋

[^7.2.5]: https://github.com/laravel/laravel/blob/2c69ec987e2dca71008684fc80bbe56c55427dc3/composer.json#L11

**Comment by innocenzi** [comment]
Hey, you're right. While I'd tend to push for newer PHP versions, it doesn't hurt to use `Route::view` in this case, so I changed this one. Thanks for pointing it out to me!
